# Generated by Django 5.0.2 on 2025-03-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationhistory',
            options={'verbose_name': 'Historial de conversación', 'verbose_name_plural': 'Historiales de conversación'},
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
