# Generated by Django 5.0.2 on 2024-12-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clientemodel_estado_del_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
