# Generated by Django 5.0.2 on 2024-12-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidadmodel',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='localidadmodel',
            name='zonas_de_interes',
        ),
    ]
