# Generated by Django 5.0.2 on 2024-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_localidadmodel_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barriomodel',
            old_name='tipo_zona',
            new_name='tipo_barrio',
        ),
        migrations.RemoveField(
            model_name='barriomodel',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='barriomodel',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='barriomodel',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='barriomodel',
            name='zonas_de_interes',
        ),
    ]
