# Generated by Django 5.0.2 on 2024-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_tipo_zona_barriomodel_tipo_barrio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonamodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='zonamodel',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='zonamodel',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='zonamodel',
            name='zonas_de_interes',
        ),
        migrations.AddField(
            model_name='zonamodel',
            name='barrios',
            field=models.ManyToManyField(blank=True, related_name='zonas', to='crm.barriomodel'),
        ),
    ]
