# Generated by Django 5.0.2 on 2024-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_edificiomodel_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificiomodel',
            name='ubicacion',
            field=models.JSONField(blank=True, help_text='\n        {\n            "latitud": "1234567890",\n            "longitud": "0987654321"\n        }\n    ', max_length=255, null=True),
        ),
    ]
