# Generated by Django 5.0.2 on 2024-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_edificiomodel_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='edificacion',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='estado_inmueble',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='honorarios',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='informacion_legal_financiera',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='zona',
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='tipo_propiedad',
            field=models.CharField(blank=True, help_text="\n        choices=[\n            ('apartamento', 'Apartamento'),\n            ('casa', 'Casa'),\n            ('local', 'Local')\n            ('terreno', 'Terreno'),\n        ]\n    ", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadmodel',
            name='direccion',
            field=models.JSONField(blank=True, help_text='\n        Formato esperado:\n        {\n            "direccion": "Calle 123",\n            "datos_adicionales": {\n                "interior": "123",\n                "torre": "A",\n                "apartamento": "101"\n            },\n            "coordenada_1": "1234567890",\n            "coordenada_2": "0987654321"\n        }\n        ', null=True),
        ),
    ]
