# Generated by Django 5.0.2 on 2024-12-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_propiedadmodel_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadmodel',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadmodel',
            name='mascotas',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadmodel',
            name='modalidad_de_negocio',
            field=models.JSONField(blank=True, help_text='\n        Formato esperado:\n        {\n            "venta_tradicional": {"activo": true, "precio": 500000000},\n            "renta_tradicional": {"activo": false, "precio": 0},\n            "renta_amoblado": {"activo": true, "precio": 3500000}\n        }\n        ', null=True),
        ),
    ]
