# Generated by Django 5.0.2 on 2024-12-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_propiedadmodel_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadmodel',
            name='modalidad_de_negocio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadmodel',
            name='tipo_propiedad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
