# Generated by Django 5.0.2 on 2024-12-12 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientemodel_cedula'),
        ('crm', '0009_alter_propiedadmodel_modalidad_de_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadmodel',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.agentemodel'),
        ),
    ]
