# Generated by Django 5.0.2 on 2024-12-13 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientemodel_cedula'),
        ('crm', '0010_alter_propiedadmodel_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadmodel',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clientemodel'),
        ),
        migrations.AlterField(
            model_name='propiedadmodel',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
