# Generated by Django 5.0.2 on 2024-12-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_propiedadmodel_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadmodel',
            name='honorarios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
