# Generated by Django 5.0.2 on 2024-12-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_propiedadmodel_amenidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidadmodel',
            name='zonas_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.zonasdeinteresmodel'),
        ),
    ]
