# Generated by Django 5.0.2 on 2024-12-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_localidadmodel_zonas_de_interes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidadmodel',
            name='zonas_de_interes',
        ),
        migrations.AddField(
            model_name='localidadmodel',
            name='zonas_de_interes',
            field=models.ManyToManyField(blank=True, to='crm.zonasdeinteresmodel'),
        ),
    ]
