# Generated by Django 5.0.2 on 2024-12-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_amenidadesmodel_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonasdeinteresmodel',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
