# Generated by Django 5.0.2 on 2024-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_zonasdeinteresmodel_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificiomodel',
            name='zonas_de_interes',
        ),
        migrations.AddField(
            model_name='edificiomodel',
            name='zonas_de_interes',
            field=models.ManyToManyField(blank=True, related_name='edificios', to='crm.zonasdeinteresmodel'),
        ),
    ]
