# Generated by Django 5.0.2 on 2024-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_remove_edificiomodel_zonas_de_interes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificiomodel',
            name='amenidades',
        ),
        migrations.AddField(
            model_name='edificiomodel',
            name='amenidades',
            field=models.ManyToManyField(blank=True, related_name='edificios', to='crm.amenidadesmodel'),
        ),
    ]
