# Generated by Django 5.0.2 on 2024-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_remove_edificiomodel_amenidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificiomodel',
            name='estado',
            field=models.CharField(default='Entregado', max_length=50),
        ),
        migrations.AddField(
            model_name='edificiomodel',
            name='tipo_edificio',
            field=models.CharField(default='Edificio Residencial', max_length=100),
        ),
    ]
