# Generated by Django 5.0.2 on 2024-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_barriomodel_zonas_de_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientomodel',
            name='presupuesto_maximo_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomodel',
            name='presupuesto_minimo_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='requerimientomodel',
            name='presupuesto_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='requerimientomodel',
            name='presupuesto_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
