# Generated by Django 5.0.2 on 2024-12-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_requerimientomodel_presupuesto_maximo_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientomodel',
            name='negocibles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomodel',
            name='no_negocibles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
