# Generated by Django 5.0.2 on 2024-12-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_caracteristicasinterioresmodel_tipo_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('description', 'Descripción de propiedad'), ('voice', 'Transcripción de voz'), ('image', 'Análisis de imagen')], max_length=20)),
                ('model_type', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o-mini'), ('gpt-4', 'GPT-4'), ('whisper', 'Whisper'), ('dalle', 'DALL-E')], max_length=20)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='puntoDeInteresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.JSONField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos/zonas/')),
            ],
        ),
        migrations.AddField(
            model_name='zonasdeinteresmodel',
            name='puntos_de_interes',
            field=models.ManyToManyField(blank=True, related_name='zonas', to='crm.puntodeinteresmodel'),
        ),
    ]
