# Generated by Django 5.0.2 on 2024-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_aiquerymodel_puntodeinteresmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonasdeinteresmodel',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='zonasdeinteresmodel',
            name='puntos_de_interes',
            field=models.ManyToManyField(blank=True, to='crm.puntodeinteresmodel'),
        ),
    ]
