# Generated by Django 5.0.2 on 2025-01-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_zonasdeinteresmodel_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barriomodel',
            name='puntos_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barrios', to='crm.puntodeinteresmodel'),
        ),
        migrations.AddField(
            model_name='edificiomodel',
            name='puntos_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios', to='crm.puntodeinteresmodel'),
        ),
        migrations.AddField(
            model_name='localidadmodel',
            name='puntos_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades', to='crm.puntodeinteresmodel'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='puntos_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.puntodeinteresmodel'),
        ),
        migrations.RemoveField(
            model_name='barriomodel',
            name='zonas_de_interes',
        ),
        migrations.RemoveField(
            model_name='edificiomodel',
            name='zonas_de_interes',
        ),
        migrations.RemoveField(
            model_name='localidadmodel',
            name='zonas_de_interes',
        ),
        migrations.AddField(
            model_name='barriomodel',
            name='zonas_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barrios', to='crm.zonasdeinteresmodel'),
        ),
        migrations.AddField(
            model_name='edificiomodel',
            name='zonas_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios', to='crm.zonasdeinteresmodel'),
        ),
        migrations.AddField(
            model_name='localidadmodel',
            name='zonas_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades', to='crm.zonasdeinteresmodel'),
        ),
    ]
