# Generated by Django 5.0.2 on 2025-03-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientemodel_cedula'),
        ('crm', '0030_agendaabiertamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaabiertamodel',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clientemodel'),
        ),
        migrations.AddField(
            model_name='agendaabiertamodel',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendaabiertamodel',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
